CREATE TABLE paises (
	id_pais CHAR(36) NOT NULL PRIMARY KEY,
	pais VARCHAR(100) NOT NULL,
	nacionalidad VARCHAR(100) NOT NULL,
	imagen_pais VARCHAR(100) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP(),
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    deleted_at DATETIME NULL
);