CREATE TABLE datos_usuarios (
	id_dato_usuario CHAR(36) NOT NULL PRIMARY KEY,
	id_usuario CHAR(36) NOT NULL,
	CONSTRAINT fk_id_usuario_datos FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE CASCADE ON UPDATE CASCADE,
	nombre_usuario VARCHAR(50) NULL,
	apellido_usuario VARCHAR(50) NULL,
	telefono_usuario VARCHAR(15) NULL,
	telefono_alternativo VARCHAR(15) NULL,
	genero_usuario ENUM ('Masculino', 'Femenino', 'Otro'),
	fecha_nacimiento_usuario DATE NULL,
	dui_usuario VARCHAR(10) NULL,
	CONSTRAINT uq_dui_usuario_unico UNIQUE (dui_usuario),
	direccion_usuario VARCHAR(200) NULL,
	id_pais CHAR(36) NULL,
	CONSTRAINT fk_pais_del_usuario FOREIGN KEY (id_pais) REFERENCES paises (id_pais),
	id_empresa CHAR(36) NULL,
	CONSTRAINT fk_empresa_del_usuario FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa),
	foto_usuario VARCHAR(50) NULL,
	perfil_red_social VARCHAR(255) NULL,
	id_tipo_identificacion CHAR(36) NULL,
	CONSTRAINT fk_tipo_identificacion_alternativa_del_usuario FOREIGN KEY (id_tipo_identificacion) REFERENCES tipos_identificaciones_alternativas (id_tipo_identificacion),
	numero_identificacion_alternativa VARCHAR(30) NULL,
	CONSTRAINT uq_numero_identificacion_alternativa_unico UNIQUE (numero_identificacion_alternativa),
	puntos_usuario INT DEFAULT 0,
	estado_civil ENUM (
		'Soltero',
		'Casado',
		'Divorciado',
		'Viudo',
		'Otro'
	) NULL,
	cargo_actual VARCHAR(50) NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP(),
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    deleted_at DATETIME NULL
);