version: '3.8'

services:
  db:
    image: mariadb:11.3
    container_name: wonderboost_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: Wonderboost
      MYSQL_USER: wonderuser
      MYSQL_PASSWORD: wonderpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: wonderboost_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/Wonderboost
      SPRING_DATASOURCE_USERNAME: wonderuser
      SPRING_DATASOURCE_PASSWORD: wonderpass
      SPRING_FLYWAY_ENABLED: "true"
    volumes:
      - .env:/app/.env

volumes:
  db_data: